apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  storageClassName: domain1
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/k8s_dir/persistentVolume001"

